BarbourSmith/Abundance

- index.html
Adds the word beta to the title 😀
> Add beta to the title

- package-lock.json
- package.json
- src/App.jsx
- src/components/secondary/SettingsPopUp.jsx
- src/js/globalvariables.js
- src/molecules/input.js
- src/molecules/output.js
- src/prototypes/atom.js
- src/prototypes/attachmentpoint.js
- src/styles/login.css
- src/styles/maslowCreate.css
- Local storage for shortcuts, themes, font size
- Added material UI as library to use input components
- Slider for atom size (connectors seem to fail when the atom size is retrieved from local storage)
- Dark theme/Light theme
> Settings pop up reconfigure

- src/js/licenseOptions.js
Makes it more clear what the available options are for folks who might not be familiar with the names
> Add small descriptions of license options

- package-lock.json
- package.json
- src/App.jsx
- src/components/main-routes/flowCanvas.jsx
- src/components/secondary/GitSearch.jsx
- src/hooks/useDebounce.js
Updates github molecule search to use useQuery hook which automatically caches previous searches making search faster overall and with more straightforward error handling. Search bar is changed to make querys as the user is typing but with a delay to avoid continuous fetching.
> Gitquery improve for github molecule search

- src/components/main-routes/LoginMode.jsx
- src/components/secondary/GitSearch.jsx
- Change initial log aws requests to use useQuery which handles caching and abort on its own.
- Rewrite components in loginMode for code clarity.
- Missing: implement "last key" and forkdummy project
> usequery for all requests

- src/worker.js
> Layout fix

- src/App.jsx
- src/components/main-routes/CallBack.jsx
- src/components/main-routes/LoginMode.jsx
- src/components/main-routes/RunMode.jsx
- src/components/secondary/RunNavigation.jsx
These changes begin to address the project fork flow for unauthenticated users. Instead of simply resetting the page, the fork button will trigger a dialog asking the user if they would like to sign in. If sign in is confirmed and authenticated, the page will redirect them back to run mode as an authenticated user.
> Forking no Login return to run

- src/App.jsx
- src/components/main-routes/CallBack.jsx
- src/components/main-routes/LoginMode.jsx
- src/components/main-routes/RunMode.jsx
- src/components/secondary/RunNavigation.jsx
Change scope of authentication so if defaults to only asking for public_repo permissions unless ?private gets added to the url at login in which case github will be asking for all repo authorization.
> Require private

- src/styles/maslowCreate.css
> Lock out selection on the top half of the screen

- src/components/secondary/Kirimoto.js
- src/molecules/gcode.js
- src/worker.js
This PR moves the generated gcode to correctly align with the position of the input parts on the work space
> Make gcode align

- src/components/main-routes/RunMode.jsx
- src/components/main-routes/flowCanvas.jsx
- src/js/globalvariables.js
- src/molecules/gcode.js
Gcode is now automatically updated in run mode because there is no way for the user to select that they want it to be regenerated
> Automatic gcode generation in run mode

- src/components/main-routes/flowCanvas.jsx
- src/components/secondary/GitSearch.jsx
- src/molecules/molecule.js
- src/styles/maslowCreate.css
- Adds catch for errors in the gitsearch github molecule API. 
- Sets an alert for the user if the project can't be found or has been deleted.
> Catch and alert for 404 on gitsearch

- Lambda AWS Functions/check-github/index.mjs
This PR enhances the Lambda function that checks GitHub repositories and manages DynamoDB records. The main improvements focus on reporting.
- **Logging and Reporting:**  
- Tracks and logs the number of projects updated, deleted, and not found.
- Sends an SES email report after every run with a summary of these actions.
- The email subject is "Abundance Check GitHub AWS Report".
- **Environment Variables:**  
Requires `GIT_ACCESS`, `SES_FROM_EMAIL`, and `SES_TO_EMAIL` to be set for authentication and email delivery. (this uses mo@maslowcnc.com as the sender (ses profile) and recipient.
> Check github email automate

- src/molecules/gcode.js
> fix gcode download

- src/worker/worker.js
Partially fixes the visualizer by doing some cleaner parsing and lowering the movement threshold.
> visualizer fix

- src/components/main-routes/CreateMode.jsx
- src/components/main-routes/RunMode.jsx
- src/components/secondary/BomMenu.jsx
- src/components/secondary/ExportMenu.jsx
- src/components/secondary/ParamsMenu.jsx
- src/components/secondary/RenderMenu.jsx
- src/components/secondary/SimpleControlPanel.jsx
- src/components/secondary/ToggleRunCreate.jsx
- src/molecules/import.js
- src/molecules/molecule.js
- src/styles/maslowCreate.css
PR Summary
Improved control panel UX: Added support for passing [maxHeight](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) and [minHeight](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) to [SimpleControlPanel](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html), ensuring these props are respected for responsive layouts.
Added debounced [onChange](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) for text and number …
> New Menu 2: Fixes and improvements

- src/components/secondary/RenderMenu.jsx
- src/prototypes/atom.js
if the input's type is "string" (or its valueType is "string"), then the [onChange](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) handler should just set the value directly, without calling [evaluateEquation](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html).
> inputParams/ string exception

- src/components/secondary/BomMenu.jsx
- src/molecules/molecule.js
BOM compile got lost in the atom computation update. I added it back to run once the worker returns the molecule computation. @tristan-huber Did you have a different plan for how BOM compile would run or does this seem ok to you?
> Bom compile fix 

- KirimotoUpdate.js
- src/molecules/gcode.js
Some errors in the progresscallback and gcodecallback props were preventing multipart gcode generation from resolving. This PR makes sure gcodecallback gets resolved, fixing the issue where parts got hung up and timed out.
> gcode handling update

- KirimotoUpdate.js
2 kirimoto outline operations enabled for the gcode process
> Kirimoto operations

- package-lock.json
- package.json
- src/App.jsx
- src/components/secondary/SimpleControlPanel.jsx
- src/molecules/BOM.js
Fixes #866 
- Makes all BOM values available as inputs
- Fixes SimplePanel missing case for "number" controls.
> BOM inputs + simplePanel number case fix

- src/components/secondary/SimpleControlPanel.jsx
Fixes #874. 
Inputs now commit value changes when they lose focus.
> Update inputs on blur

- src/App.jsx
- src/components/main-routes/CallBack.jsx
- src/components/main-routes/CreateMode.jsx
- src/contexts/AuthContext.jsx
- Fix Minor redirect issues with new auth flow
- Change variable name for clarity
> Fix Minor redirect issues with new auth flow

- package-lock.json
- src/molecules/molecule.js
- tests/copy-paste-uniqueness.test.js
- tests/issue-900-validation.test.js
Fixes #900 
This is the same as #905, but before the AI made it's last set of changes which made things worse 😛
> Fix copying and pasting molecules with github atoms

- src/App.jsx
- src/molecules/import.js
- src/molecules/molecule.js
Restore render-by-default behavior for the top level molecule. Fixes #908
> Runmode fix

- src/components/secondary/NewProjectPopUp.jsx
> Fixes #920 - Corrects variable assignment in new project

- src/worker/actions.ts
> Fix rotate action for planar objects

- src/molecules/code.js
"const Inputs" replaces "Inputs".
> Declare Inputs in the code example

- .vscode/launch.json
- Lambda AWS Functions/update-AP-rankings/lambda_function.py
- src/components/secondary/RunNavigation.jsx
NEW RANKINGS ARE IN!!!
Instead of using likes alone, our rankings now use a combinations of likes, forks, and times the molecule is used in other projects as a github molecule to calculate the project's ranking! The rankings are calculated weekly in an AWS function "update-AP-rankings". This change also allows us to get rid of a couple invokations to aws in our runnavigation flow since we no longer need to update the ranking of the project when its liked and can just gather the data from the user table weekly.
> RANKING #1

- src/App.jsx
- src/components/secondary/RenderProgressBar.jsx
- src/styles/login.css
quick changes to render bar. Still could use some improvements to track output ready changes.
> Render bar legibility + fix initial complete label

- src/components/main-routes/RunMode.jsx
There was an error in the logic of the runMode use effect which prevented loading of projects if there was already another project loaded.
> run mode redirection bug fix
