src/worker.js

The difference function (and subsequently the assembly function) were depending on fusing all of the inputs in an assembly together before cutting which is slow and inefficient.
This change makes it so that each part is cut individually and bounding boxes are checked before the cut takes place to make sure that parts which don't intersect will not be cut (basically we can skip them if they don't touch).

Make assembly not use fuse

---

src/molecules/input.js
src/prototypes/attachmentpoint.js

This should fix #333 by relating the x of the input atom to the variable size of the atoms which can be changed by the user.
Input is a special case for attachment point since it's shape is rectangular and not circular and such needs a different expand and retract radius than other outputs.

Input - expand/unexpand bug fix 

---

src/components/secondary/codeWindow.jsx
src/molecules/code.js
src/worker.js

Minor improvements for the code molecule. No longer use eval, instead use a supposedly safer approach of wrapping the code in a function def and executing that. Also adds some banned keywords to the code molecule. We probably want to reduce this list at some point (eg: it currently includes 'import' but we probably eventually want to allow users to import external libraries).
Ideally we'd have a user warning with override option whenever a banned keyword is found.
Only other change,
ctrl+s (or cmd+s) inside the editor now saves the code instead of opening a save-to-file prompt from the browser. Notably, this does not trigger a save of the project though it maybe should.

Code molecule

---

src/worker.js

It was not allowed as a dangerous pattern, but it doesn't seem that dangerous and it's very helpful or even necessary when interacting with replicad functions which call for a function pointer.

Allow /Function Within Code Atom

---

src/components/main-routes/flowCanvas.jsx

A break in double click was preventing molecules from being entered. Removing the break fixes the issue.

Fix double click break

---

src/components/secondary/GitSearch.jsx

Prevent user click on github search list items if the search hasn't finished to prevent sequence issues.

Github search disable items if loading

---

src/components/secondary/ParameterEditor.jsx
src/molecules/import.js

This pull request takes care of updating the leva menu on the import atom if a file has been updated. It allows the user to immediately see the name of the file that has been uploaded and leaves the load button enabled allowing for a different upload to the atom. 
A subsequent pull request will address some issues with files not being deleted from the repo as well as user alerts letting them know the import has been deleted. 
Fixes #581

Import leva menu update

---

src/molecules/code.js

I have been hunting this one for a while so i'm singing a hesitant victory but I think this takes care of the input resetting issues that we have been seeing in the code atom. The problem seemed to be that setvalues and parse inputs kept resetting the inputs to the default values in updateValue. There is still an issue with the github molecules that contain code atoms so this doesn't fix  #612 but should make it much easier to track down.

Input bug in code fix

---

src/App.jsx
src/prototypes/atom.js
src/worker/actions.js
src/worker/code.js
src/worker/cutlayout.js
src/worker/interaction.js
src/worker/shapes.js
src/worker/tags.js
src/worker/util.js
src/worker/worker.js
tests/actions.test.js
tests/code.test.js
tests/extrude.test.js
tests/interaction.test.js
tests/shapes.test.js
tests/tags.test.js

Moves worker.js into a folder so that it's functions can be split into multiple files.
Big picture goals here are two-fold:
1) move some of the logic of worker.js into separate files so that it's easier to tell which functions are related and what depends on what
2) set up apis which are more stateless and easier to test, eg: the new cutlayout.js file does not directly interact with the library object. All of the context (besides replicad itself) is provided as arguments and all of the effects are returned as results.
In this pr cutlayout.js is serving as an example of the kind of decomp I'd like to apply more generally. I'm not sure it's necessary to have a file for each atom. Eg: extrude so straight forward I'm not sure it helps readability to be in it's own file. There's a couple …

Move worker.js so it can start to be deomposed

---

src/components/secondary/ParameterEditor.jsx

Fixes #500 
When you type a single number into the input field for current equation the input type remains a string instead of resetting to a number type which caused the currentEquation input to break. 
There is still an issue where if there's no variables the equation will not compute the correct result.

Fix equation stuck with numeric value

---

src/molecules/import.js

Fixes #726 
- If an imported file is not found as a result of a file that was uploaded but not committed and returning a 404 from github, file name, sha and loaded file info will be clear to make the atom available for a different file upload.

Error handling for 404 import

---

src/molecules/equation.js

This PR improves the Equation atom to support referencing parent molecule input atoms directly as variables in equations 
- When evaluating an equation, the atom now substitutes variables using parent molecule inputs first, then falls back to its own inputs, and finally defaults to 0 if not found.
This allows equations like [x - 3 / width] to use immediate molecule-level variables seamlessly.
- The [addAndRemoveInputs] method now only adds IOs for variables that are not present in the parent molecule's inputs.
If a variable matches a molecule input, it will not be added as an equation atom input, preventing duplicate IOs and ensuring correct data flow.

Basic Inline Equation inputs

---

KirimotoUpdate.js

Still have some issues with pass count but this should fix one major issue in generating gcode where although a new stl was being passed to the engine, the bounding box was not updated.
- The boundingbox method is now updated and should retrieve the correct box.
- Resets stock thickness and center to account for a margin and the cut through. 
- Sets ZcamBottom as the total part depth plus cutthru
- Sets down to use zbottom as the total depth from which passes are calculated.

kirimoto zbottom issue and bounding box update

---

KirimotoUpdate.js
src/molecules/gcode.js

Ok so this is not right but it makes it so that the visualizer loads at the correct scale. Projects in MM were loading correctly with the copilot unit changes but soon after I merged it realized that projects in inches were still loading incorrectly (too small). I'm not sure why this is. I corrected the missing units parameter in the stl generation and hoped that would fix it but this change to MM in the pregcode setting seems to generate the same size as the piece.

Unit correction for STL generation and unit pregcode change

---

src/molecules/gcode.js

This should fix the extra sendtorender calls that made the interface look glitchy after the gcode was automatically generated

Fix render issue generated by auto generate gcode

---

src/molecules/equation.js
src/molecules/molecule.js
src/molecules/rectangle.js
src/prototypes/atom.js

@tristan-huber and @BarbourSmith I wanted to get your eye on this feature. It implements an enhancement we discussed: molecule inputs can now be referenced as variables in any atom input. For example, if a molecule has inputs named "thickness1" and "tolerance", you can set an Extrude atom’s height to thickness1 / tolerance, and it will be evaluated as an equation.
Inputs now serialize both the equation and its result, so the original equation is displayed and re-evaluated, not just the computed value.
One downside is that, since all inputs are now treated as strings, you lose the ability to increment/decrement numeric values with the arrow keys—you’ll need to type them out manually.
Most basic atoms should work with this update. Please try it out and let me know your thoughts!

Equation and variable eval in atom inputs

---

src/molecules/extracttag.js
src/molecules/input.js

If an input's default value was falsey it would get stuck in "waiting". We now refer to the parent AP's status to determine the input status instead of checking the truthiness of it's value

Fix issue where inputs got stuck in "waiting" state

---

KirimotoUpdate.js
src/molecules/gcode.js

@BarbourSmith  !!!!!!!!  I found a fix to the gcode 1 pass issue, at least a temporary one. What seemed to fix it was buried in a response to one of our first kirimoto forum posts, and is indeed caused by the setZtop issue. 
This is the blog post where BakedPotato outlines a hack to get rid of the extra pass: https://forum.grid.space/t/cam-kirimoto-api-help/2511/21
So for now what I'm doing is hardcoding a really high value to "down" when 1 pass is selected. I also separated the outside and inside passes so the inside runs first. 
This PR also sets gcode to have a tool array from which the user can select from but I have left it disabled for now.

Gcode 1 pass fix - temporary dependent on kiri fixes 

---

src/molecules/code.js

When inputs are added in the code atom, saveCode triggers a setInputChange so the menu reloads dynamically

Handle input change in code

---

src/prototypes/atom.js
src/prototypes/attachmentpoint.js

@alzatin This fixes part of the issue we were texting about!
The new menu is looking sick! And that change fixed the issue where default values were getting propagated instead of the real value from a const or input (in fact this affected all connected numeric attachmentPoints).
This PR fixes the last part of the issue which is that we could end up in this weird state where the correct value is being used but the outdated "currentEquation" value (in these cases a numeric literal) was being displayed. We now disregard the saved `currentEquation` if it's a numeric literal and just display the value itself.
There is still one related issue which will be a more involved fix. Specifically if an input holds an equation and one of the inputs to that equation is changed it doesn't recompute the …

Fix: outdated values were shown in ParamMenu

---

KirimotoUpdate.js

Fiddling some more with kirimoto settings. 
@BarbourSmith 
- These settings result in the right piece depth and correct number of passes. I added the cut through to the stock depth which seems to allow us to compute the right down value with no extra passes but i don't see the cut through value reflected in the visualizer so not sure what's up with that.
- Although the operation that is uncommented gives the correct number of passes, i haven't been able to separate the operations into interior and exterior because for some reason the "ouside only" setting forces a bunch of extra passes 👎 . So the current operation does both, which i'm guessing is not ideal.
- I think there's currently an issue with multiple parts but i think this is related to the new atom computing changes and where the …

GCODE - right # passes 

---

src/components/main-routes/CreateMode.jsx
src/components/main-routes/RunMode.jsx
src/components/secondary/SimpleControlPanel.jsx

This PR syncs uncollapsed/collapse states for all the new menu dropdowns so only one panel can be open at a time.

Single state for expanded menu

---

src/components/main-routes/CreateMode.jsx
src/molecules/code.js
src/prototypes/atom.js

Focus code window issue fix: 
New panels were forwarding keydown to panel even if code window was open which made the codewindow uneditable. This prevents the ref forwarding if window by checking the window styling. Considering that code can and will often have editable inputs and we want it to behave the same as other atoms, i will in the future switch code window opening and closing to be set by state management instead of styling which would let us forward the key to the panel is the code window is not open. 
Code Input issues: 
Input valueType and defaultValue for code inputs were not being respected if the inputs already existed. Switches to using atoms createInputParams function instead of repeating in code atom.

Fix codewindow keydown focus and code input valuetype bug

---

src/components/secondary/RunNavigation.jsx
src/prototypes/atom.js

When runmode does not have an authorized user it displays the fork button. However if the users clicked the fork button and logged in but the project was their own, it overwrote the parentRepo values so that the fork lost its parentRepo information making it impossible to reload from its parent Repo.
This PR prevents a user from being able to run the forkRepo function on a repo they own and instead redirects them to the project.

Prevent forking if you own the project

---

src/molecules/molecule.js

Projects larger than 100mb can't be retrieved using the github getcontent API which is why some projects like "Sauna-Trailer" were failing to reload. This PR adds a fetch alternative to fetch from the download_url instead of using the restAPI which is how we load large projects as well.

Add alternate fetch to reload forks for large projects

---

src/components/main-routes/CreateMode.jsx
src/components/main-routes/flowCanvas.jsx

- Collapse any side menu and expand param menu if active atom is set or if there's a background click on canvas.
@BarbourSmith My guess on the molecule and tag bug you saw is that the gitsearch menu was open but you were actively trying to edit the params menu to edit the molecule and tag names.

Collapse Side menu

---

src/components/secondary/RunNavigation.jsx

We can now use currentAWSnode in the likeProject function instead of building a node from scratch

Fixing like project metadata

---

src/molecules/BOM.js
src/molecules/constant.js
src/molecules/difference.js
src/molecules/extrude.js
src/molecules/gcode.js
src/molecules/loft.js
src/molecules/shrinkWrap.js

Fixes #957
Draw erroneous icons relative to the atom's center in pixel space so that they keep their position and size as the screen resizes.

CANVAS icons fix

---

src/molecules/gcode.js
src/worker/worker.ts

issue: gcode molecule wouldn't become ready on input change.
I missed a code path into `generateSequencialGcode` so in the auto-compute case the gcode would be generated and rendered but because the molecule didn't get `setReady` with the value, the rendered gcode wasn't saved. So if you clicked away and clicked back the gcode would vanish.
Fixed by moving the `setProcessing` and `setReady` calls into generateSequencialGcode. Note this doesn't fix for the non-assembly case.

Gcode molecule state fixes

---

src/worker/geometryProvider.ts
src/worker/interaction.ts
src/worker/worker.ts

This is a stop-gap to avoid crashing. Longer term we should move to a thumbnail strategy which doesn't require fusing.
This PR also introduces an optimized fuse for assemblies, though the performance improvement is only moderate.

Don't attempt thumbnail generation for projects with > 100 parts.

---

src/components/render/ThreeContext.jsx
src/components/render/ThreeControls.jsx

Fixes #997
- Update to a new version of the drei Gizmo Helper which can snap to different views and has a clearer indicator of X+ or Y+ direction.
- Adds center marker and axes helper to demarcate the x/y/z plane

Updated grid gizmo/Center helper
